### ISSUE TITLE
Fix: add Prettier button for issues (new and existing)

### ISSUE THREAD

**Issue by kaicataldo** [prettier/prettier-chrome-extension#14]

**Comment by nickmccurdy** [comment]
#19 works for me when commenting and editing existing issues, but not when creating new issues.

**Comment by Wicked7000** [comment]
@nickmccurdy I can see the button when creating issues - Do you still see this as I can't seem to find a case on my side where it is not working.

**Comment by nickmccurdy** [comment]
I tried it again in this repo and it seems to be working fine now. Can be closed, I'll make another issue if I find a reproducible regression.

**Comment by kaicataldo** [comment]
LGTM!
<img width="1040" alt="Screen Shot 2019-10-14 at 10 39 30 PM" src="https://user-images.githubusercontent.com/7041728/66795737-81850780-eed3-11e9-9409-326d2a2dd7d8.png">
