### ISSUE TITLE
Fix: figure out a better way to render the GitHub comment buttons

### ISSUE THREAD

**Issue by kaicataldo** [prettier/prettier-chrome-extension#15]
The GitHub buttons currently wait until a user starts typing before rendering. It would be great to figure out some way to know when a new comment is created (maybe an `onclick` listener, filtering out by what element was clicked and checking the existence of a new comment?). We should be able to traverse the DOM for to find the relevant `textarea` when the Prettier button is clicked, so it should be able to be a fairly naive check just to scan for any editable textareas that don't have a button.

**Comment by nickmccurdy** [comment]
Fixed by #19
