### ISSUE TITLE
Options link in extension options has broken link

### ISSUE THREAD

**Issue by nickmccurdy** [prettier/prettier-chrome-extension#244]
I'm not sure why this is happening, as it should be opening in a new tab

![image](https://user-images.githubusercontent.com/927220/84302895-105e2880-ab24-11ea-90fe-008589730003.png)

**Comment by sibiraj-s** [comment]
I checked. works fine for me 🤔

**Comment by nickmccurdy** [comment]
That's odd. Do you think you could send me your extension build (preferably as a ZIP file or some downloadable folder) so I can test it out?

**Comment by sibiraj-s** [comment]
Yeah I doesn't work in Google Chrome, I was using brave for development, it worked fine there. I raised a fix for it.
