### ISSUE TITLE
Config support

### ISSUE THREAD

**Issue by nickmccurdy** [prettier/prettier-chrome-extension#25]
https://github.com/prettier/prettier-chrome-extension/pull/23#issuecomment-541471476

**Comment by kaicataldo** [comment]
Definitely think we should implement this! Assuming we want this in the extension's settings page, seems like we could:

1) Have a text input that accepts JSON
2) Have individual inputs for each configurable option (I think VS Code's plugin does this?)
3) Both of the above!

**Comment by nickmccurdy** [comment]
As far as UI is concerned, I really like how [Code Sandbox](https://codesandbox.io) does it. There's a preference pane with a GUI for the Prettier fields and a link to edit the JSON directly for importing/exporting (similar vibe to VSCode's user/workspace settings).

![image](https://user-images.githubusercontent.com/927220/66870069-a8dce280-ef6e-11e9-9b84-7beeeba9900a.png)
![image](https://user-images.githubusercontent.com/927220/66870126-bd20df80-ef6e-11e9-819b-42acf83e917c.png)

__Source:__ https://github.com/codesandbox/codesandbox-client/blob/master/packages/app/src/app/pages/common/Modals/PreferencesModal/CodeFormatting/Prettier/index.tsx

**Comment by kaicataldo** [comment]
That seems pretty ideal to me.

**Comment by nickmccurdy** [comment]
Would you be okay with pulling in React for this? It will require some build configuration which I can help with, but it's pretty small and will make managing the form a lot easier.

**Comment by kaicataldo** [comment]
I'm not opposed to that at all! The current plugin code uses vanilla JS because there really isn't much UI to render.

**Comment by lipis** [comment]
Yes, I also don't mind React.. as long as it's nice and tidy..! :)

**Comment by nickmccurdy** [comment]
I just realized the playground is using React, would it be better to try to reuse those components instead of cloning Code Sandbox's UI? It has sections and I figure it might be more familiar to Prettier users, though I think Code Sandbox's looks nicer

**Comment by kaicataldo** [comment]
Oh, that's interesting. It looks like there are a number of configuration options in the playground that we probably wouldn't use. I wonder if it's worth the overhead of extracting out a package that we have to make sure works for both cases? Given that there isn't a ton of complex behavior, I'm inclined to say we just write our out config UI. I'm happy to go with consensus on this though :)

**Comment by nickmccurdy** [comment]
We could start by copying it if we like the playground UI, and extract a package if we end up using shared logic. Do you have any preference over this UI or the code sandbox one?

**Comment by kaicataldo** [comment]
I think that seems like a good plan! I didn't have any particular design choices in mind. I like the idea of making it an [embedded option](https://developer.chrome.com/extensions/options#embedded_options), because then you can just style the popup and not have to worry about how it looks in a full document. I think the Redux DevTools use this nicely:

<img width="733" alt="Screen Shot 2019-10-17 at 9 32 30 PM" src="https://user-images.githubusercontent.com/7041728/67059159-ea63be00-f125-11e9-97af-4c80cdf589eb.png">
<img width="703" alt="Screen Shot 2019-10-17 at 9 32 36 PM" src="https://user-images.githubusercontent.com/7041728/67059160-ea63be00-f125-11e9-855a-c2767054f5e8.png">

**Comment by nickmccurdy** [comment]
That's a good idea, I think it would make formatting easier.
