### ISSUE TITLE
Maybe including the main.js in the repo?

### ISSUE THREAD

**Issue by lipis** [prettier/prettier-chrome-extension#29]
What about committing to the repo the main.js as well so it will be just clone and update :)

**Comment by nickmccurdy** [comment]
In my opinion it's bad practice to commit built artifacts. However I just saw #28 which seems like a better approach to me.

**Comment by lipis** [comment]
People still need to run build, which from extension point of view it's a hassle.

But on the other hand we need to release quite fast.. so people could install it via the market.. Is it ready yet?

**Comment by nickmccurdy** [comment]
I know #28 was merged, but do you think we could automate releasing the extension easier? I'm not sure if the Chrome Web Store itself supports automating it, but maybe we could at least pack it from the scripts.
