### ISSUE TITLE
Button is missing `type="button"` attribute

### ISSUE THREAD

**Issue by OliverJAsh** [prettier/prettier-chrome-extension#44]
This means it may submit the form it lives inside, which is probably not desired…

![Screen Recording 2019-10-16 at 18 15 12](https://user-images.githubusercontent.com/921609/66942433-ff1a5600-f040-11e9-938f-9578c75f22f0.gif)

**Comment by nickmccurdy** [comment]
Good catch, I think that also affects accessibility

**Comment by kaicataldo** [comment]
This didn't happen with the original implementation - I wonder if the buttons are being rendered in a different place? Might be a regression caused by https://github.com/prettier/prettier-chrome-extension/commit/befe1fbea6c4ebadb3ad0d271046893ce48fd7a7.
