### ISSUE TITLE
Cross browser support with WebExtensions

### ISSUE THREAD

**Issue by nickmccurdy** [prettier/prettier-chrome-extension#46]
Supporting multiple browsers used to involve writing a different codebase for each set of APIs, but now most major browsers support the WebExtensions standard. I’m guessing the next most requested browser would be Firefox, but we could do a poll to figure out what browsers Prettier users would like to use and research from there.

**Comment by kaicataldo** [comment]
This seems useful and would require minimal changes to the current codebase: https://github.com/mozilla/webextension-polyfill#basic-setup-with-module-bundlers

**Comment by nickmccurdy** [comment]
It says that it doesn’t do anything on Firefox, but adds support for some Firefox features to Chrome extensions. Are the `chrome` APIs already supported on Firefox, or does this mean we’ll need to change to using Firefox’s web extensions APIs to use the polyfill?

**Comment by nickmccurdy** [comment]
I can install the extension on Firefox, but the it doesn't appear to be loading anything (no icon/content/options). I've tried this with and without `webextension-polyfill`.

**Comment by sibiraj-s** [comment]
@nickmccurdy .

```
"applications": {
    "gecko": {
      "id": "@prettier",
      "strict_min_version": "54.0"
    }
  },
``` 

add this to the manifest json, it will work. I am not sure why this is required for testing extensions though.

Plus the icon won't show-up in the toolbar as it does in chrome. we need to add icons under browser_actions, the rest should work without any issues.

**Comment by nickmccurdy** [comment]
In macOS Big Sur (releasing this fall), WebExtensions will be officially supported by Safari, and Apple will provide distribution through the Mac App Store along with a Chrome extension migration tool. If anyone wants Safari support this seems promising, but it looks like we would either have to make users download the extension manually or pay up for the developer account feeds ($100 USD/year).
