### ISSUE TITLE
Fix button styling/location for GitHub

### ISSUE THREAD

**Issue by kaicataldo** [prettier/prettier-chrome-extension#64]
The buttons are currently being rendered in such a way that they change the flow of the buttons row. Can we figure out a way for them not to do this?

**Comment by nickmccurdy** [comment]
I'm not sure I understand the issue. In devtools the button seems to be appended at the beginning like I expected. Is it supposed to be a child of the parent div instead?

![image](https://user-images.githubusercontent.com/927220/68055046-2ff7bd80-fcc6-11e9-8366-0d439382b0f2.png)
