### ISSUE TITLE
Move files to root and publish the dist directory directly

### ISSUE THREAD

**Issue by nickmccurdy** [prettier/prettier-chrome-extension#67]
https://github.com/prettier/prettier-chrome-extension/pull/56#issuecomment-545709825

**Comment by kaicataldo** [comment]
I think we're currently including the `src` directory in the distributed plugin. We could very easily move everything to the root and use `WebpackCopyPlugin` to copy in whatever other files we need (currently just `icons` and `manifest.json`, I think)?
