### ISSUE TITLE
JSON config import/export

### ISSUE THREAD

**Issue by nickmccurdy** [prettier/prettier-chrome-extension#68]
https://github.com/prettier/prettier-chrome-extension/pull/23#issuecomment-541471476

**Comment by nickmccurdy** [comment]
Any preferences on whether this should be part of 1.0?

**Comment by kaicataldo** [comment]
I think this would be nice to implement for v1, but we should finish the current settings panel first.

**Comment by kaicataldo** [comment]
It actually sounds like we had a different idea of what this feature actually is. I wanted to add a text box where users could paste in their local config, and it sounds like the proposal here is to actually import and export from the file system. I don’t think these two features are mutually exclusive - in fact, the import button could populate the text box.

**Comment by nickmccurdy** [comment]
Sorry, I think I was too vague in explaining the UI I was thinking of. Basically, I'd like a JSON input as an alternative to the form, where users can switch back and forth at any time using the same config. This is exactly what [Code Sandbox](https://codesandbox.io/) does, and our form UI is already based on theirs. The thing I like about this is that we don't need to worry about creating separate import/export UI when users can edit the config either way.

> I wanted to add a text box where users could paste in their local config
That's what I intended.

> it sounds like the proposal here is to actually import and export from the file system
That's not what I intended, but since Chrome extensions have more access to the file system, we could potentially add this.

> the import button could populate the text box
I was thinking of this, except that

**Comment by kaicataldo** [comment]
> Sorry, I think I was too vague in explaining the UI I was thinking of. Basically, I'd like a JSON input as an alternative to the form, where users can switch back and forth at any time using the same config. This is exactly what Code Sandbox does, and our form UI is already based on theirs. The thing I like about this is that we don't need to worry about creating separate import/export UI when users can edit the config either way.

Ah okay, thanks for explaining that. I'm not against doing that!

> I wouldn't prioritize it though, as it's easy to copy and paste your config as JSON, and users probably won't need to import/export their config more than once.

Agreed, I don't think this should be a blocker for v1.
