### ISSUE TITLE
Any todo or list of features needs to add for this project

### ISSUE THREAD

**Issue by anikethsaha** [prettier/prettier-chrome-extension#9]
I saw the other two issue about the adding the button for stackoverflow and github and which is covered in #3 , which is pretty awesome and loved the current implementation of that. 
Is there any other list of thing need to do for this project were contributions can be done . I would be happy to help in those. I guess adding a todo list anywhere in the readme or a separate pinned issue for that will work good. 

Really liked the idea of this extension 👌👌👍👍

**Comment by lipis** [comment]
We'll merge that one pretty soon and I'm sure there are plenty of things that will need to be done.. #8 is one of them :)

**Comment by lipis** [comment]
I think now there quite a few items to pick from, so I'm closing this one.
